name: build
on:
  push:
    branches: ["master"]
    paths-ignore: ["README.md", "images/*"]
  pull_request:
    branches: ["master"]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        sudo apt-get install -y libvlccore-dev mingw-w64
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        cmake -B build/win64 -S . --toolchain ./toolchains/mingw-win64.cmake -DCMAKE_BUILD_TYPE=Release
        cmake --build build/win64
        cmake -B build/win32 -S . --toolchain ./toolchains/mingw-win32.cmake -DCMAKE_BUILD_TYPE=Release
        cmake --build build/win32
    - uses: actions/upload-artifact@v4
      with:
        name: vlcrm_linux
        path: build/libvlcrm_plugin.so
    - uses: actions/upload-artifact@v4
      with:
        name: vlcrm_win64
        path: build/win64/libvlcrm_plugin.dll
    - uses: actions/upload-artifact@v4
      with:
        name: vlcrm_win32
        path: build/win32/libvlcrm_plugin.dll
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        cmake -B build/intel64 -S . --toolchain ./toolchains/macos-intel64.cmake -DCMAKE_BUILD_TYPE=Release
        cmake --build build/intel64
    - uses: actions/upload-artifact@v4
      with:
        name: vlcrm_macos_arm64
        path: build/libvlcrm_plugin.dylib
    - uses: actions/upload-artifact@v4
      with:
        name: vlcrm_macos_intel64
        path: build/intel64/libvlcrm_plugin.dylib