name: build
on:
  push:
    branches: ["master"]
    paths-ignore: ["README.md", "images/*"]
  pull_request:
    branches: ["master"]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: |
        sudo apt-get install -y libvlccore-dev mingw-w64 mingw-w64-common
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
        cmake --build build
        cmake -B build/win64 -S . -DCMAKE_BUILD_TYPE=Release --toolchain ./toolchains/mingw-w64.cmake 
        cmake --build build/win64
        cmake -B build/win32 -S . -DCMAKE_SYSTEM_PROCESSOR=i686 -DCMAKE_BUILD_TYPE=Release --toolchain ./toolchains/mingw-w64.cmake
        cmake --build build/win32
    - uses: actions/upload-artifact@v4
      with:
        name: vlcrm_linux
        path: build/libvlcrm_plugin.so
    - uses: actions/upload-artifact@v4
      with:
        name: vlcrm_win64
        path: build/win64/libvlcrm_plugin.dll
    - uses: actions/upload-artifact@v4
      with:
        name: vlcrm_win32
        path: build/win32/libvlcrm_plugin.dll
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
        cmake --build build
    - uses: actions/upload-artifact@v4
      with:
        name: vlcrm_macos
        path: build/libvlcrm_plugin.dylib