name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt-get install -y libvlccore-dev
    - run: cmake -B build -S . -DCMAKE_BUILD_TYPE=Release
    - run: cmake --build build
    - uses: actions/upload-artifact@v4
      with:
        name: libvlcrm_plugin.so
        path: build/libvlcrm_plugin.so
